<h1>PERSONALITY PREDICTION THROUGH CV ANALYSIS</h1>

In [37]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv('training_dataset.csv')

In [3]:
df.head()

,Gender,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion,Personality (Class label)
0,Male,17,7,4,7,3,2,extraverted
1,Male,19,4,5,4,6,6,serious
2,Female,18,7,6,4,5,5,dependable
3,Female,22,5,6,7,4,3,extraverted
4,Female,19,7,4,6,5,4,lively

<H1>PRE PROCESSING</H1>

In [5]:
df.describe()

,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion
count,709.000000,709.000000,709.000000,709.000000,709.000000,709.000000
mean,19.685472,5.019746,4.647391,4.643159,4.827927,4.409027
std,2.510672,1.519052,1.658673,1.703569,1.632564,1.567404
min,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,18.000000,4.000000,4.000000,3.000000,4.000000,3.000000
50%,19.000000,5.000000,5.000000,5.000000,5.000000,5.000000
75%,21.000000,6.000000,6.000000,6.000000,6.000000,6.000000
max,28.000000,8.000000,8.000000,8.000000,8.000000,7.000000

In [7]:
df.columns

Index(['Gender', 'Age', 'openness', 'neuroticism', 'conscientiousness',
       'agreeableness', 'extraversion', 'Personality (Class label)'],
      dtype='object')

In [14]:
df=df.dropna()

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()

In [19]:
df['Gender']=le.fit_transform(df['Gender'])
df['Personality (Class label)']=le.fit_transform(df['Personality (Class label)'])

In [21]:
df

,Gender,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion,Personality (Class label)
0,2,17,7,4,7,3,2,1
1,2,19,4,5,4,6,6,4
2,1,18,7,6,4,5,5,0
3,1,22,5,6,7,4,3,1
4,1,19,7,4,6,5,4,2
...,...,...,...,...,...,...,...,...
704,1,20,4,5,6,6,1,3
705,2,18,6,3,1,5,5,0
706,2,22,5,2,3,6,1,4
707,2,19,5,6,5,7,5,1
708,1,18,5,5,7,6,5,1

<H1>MODEL FITTING</H1>

In [63]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [64]:
x

,Gender,Age,openness,neuroticism,conscientiousness,agreeableness,extraversion
0,2,17,7,4,7,3,2
1,2,19,4,5,4,6,6
2,1,18,7,6,4,5,5
3,1,22,5,6,7,4,3
4,1,19,7,4,6,5,4
...,...,...,...,...,...,...,...
704,1,20,4,5,6,6,1
705,2,18,6,3,1,5,5
706,2,22,5,2,3,6,1
707,2,19,5,6,5,7,5
708,1,18,5,5,7,6,5

In [65]:
y

0      1
1      4
2      0
3      1
4      2
      ..
704    3
705    0
706    4
707    1
708    1
Name: Personality (Class label), Length: 709, dtype: int32

In [66]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [67]:
lr=LogisticRegression()

In [68]:
lr.fit(xtrain,ytrain)

C:\Users\Harshal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [69]:
pred=lr.predict(xtest)

In [70]:
acc=accuracy_score(pred,ytest)
print(acc)

0.20657276995305165

<H1>GUI</H1>

In [ ]:
import tkinter as tk
from tkinter import ttk, filedialog

class PersonalityForm(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Personality Form")
        self.configure(bg='#006400')  
        self.create_widgets()

    def predict(self):
        # Get user input from the GUI
        applicant_name = self.name_entry.get()
        age = int(self.age_entry.get())
        gender = self.gender_var.get()
        openness = self.sliders[0].get()
        neuroticism = self.sliders[1].get()
        conscientiousness = self.sliders[2].get()
        agreeableness = self.sliders[3].get()
        extraversion = self.sliders[4].get()

        # Example: Create a feature vector based on user input
        features = [age, openness, neuroticism, conscientiousness, agreeableness, extraversion]

        # Add gender as a numeric feature (assuming Male=0, Female=1)
        gender_numeric = 0 if gender == "Male" else 1
        features.insert(0, gender_numeric)

        # Example: Make a prediction using your machine learning model
        prediction = lr.predict([features])

        personality_traits = self.convert_to_personality_traits(prediction[0])

        # Display the prediction on the GUI
        ttk.Label(self, text=f"Prediction for {applicant_name}: {personality_traits}", background="#006400", font=(10), foreground="#fff").grid(row=9, column=0, padx=5, pady=5, sticky="w")

    
    def convert_to_personality_traits(self, prediction):
        # Convert numeric prediction to specific personality traits
        traits_dict = {0: "Openess", 1: "neuroticism", 2: "conscientiuusness", 3: "agreeableness", 4: "Extraversion"}
        return traits_dict.get(prediction, "Unknown Trait")


        # Example: Display the prediction (you may want to update this based on your application)
        print(f"Prediction for {applicant_name}: {prediction}")

    def create_widgets(self):
        # Create a frame to hold the form widgets
        form_frame = ttk.Frame(self, padding=(20, 10), style="My.TFrame")
        form_frame.grid(row=0, column=0, sticky="nsew")

        # Apply a custom style to the frame
        self.style = ttk.Style(self)
        self.style.configure("My.TFrame", background='#006400')  

        # Applicant Name
        ttk.Label(form_frame, text="Applicant Name:", background="#006400", font=(10), foreground="#fff", style="Bold.TLabel").grid(row=0, column=0, padx=5, pady=5, sticky="w")
        self.name_entry = ttk.Entry(form_frame)
        self.name_entry.grid(row=0, column=1, padx=5, pady=5, sticky="w")

        # Age
        ttk.Label(form_frame, text="Age:", background="#006400", font=(10), foreground="#fff", style="Bold.TLabel").grid(row=1, column=0, padx=5, pady=5, sticky="w")
        self.age_entry = ttk.Entry(form_frame)
        self.age_entry.grid(row=1, column=1, padx=5, pady=5, sticky="w")
        
        # Gender
        ttk.Label(form_frame, text="Gender:", background="#006400", font=(10), foreground="#fff", style="Bold.TLabel").grid(row=2, column=0, padx=5, pady=5, sticky="w")
        self.gender_var = tk.StringVar()
        self.gender_var.set("Male")
        ttk.Radiobutton(form_frame, text="Male", variable=self.gender_var, value="Male", style="My.TRadiobutton").grid(row=2, column=1, padx=5, pady=5, sticky="w")
        ttk.Radiobutton(form_frame, text="Female", variable=self.gender_var, value="Female", style="My.TRadiobutton").grid(row=2, column=2, padx=5, pady=5, sticky="w")

        # Resume Upload
        ttk.Label(form_frame, text="Upload Resume:", background="#006400", font=(10), foreground="#fff", style="Bold.TLabel").grid(row=3, column=0, padx=5, pady=5, sticky="w")
        self.upload_button = ttk.Button(form_frame, text="Browse",style="My.TButton", command=self.browse_resume)
        self.upload_button.grid(row=3, column=1, padx=5, pady=5, sticky="w")

        # Personality Traits
        traits_frame = ttk.LabelFrame(form_frame, text="Personality Traits", padding=(10, 5), style="My.TLabelframe")

        # Personality Traits traits_frame = ttk.LabelFrame(form_frame, text="Personality Traits", padding=(10, 5), style="My.TLabelframe")
        traits_frame.grid(row=4, column=0, columnspan=3, pady=10, sticky="nsew")

        # Apply a custom style to the labeled frame
        self.style.configure("My.TLabelframe", background='#008000', forground="#fff")  

        labels = ["Openness", "Neuroticism", "Conscientiousness", "Agreeableness", "Extraversion"]
        self.sliders = [ttk.Scale(traits_frame, from_=0, to=10, orient="horizontal") for _ in range(5)]

        for i, label in enumerate(labels):
            ttk.Label(traits_frame, text=f"{label}:", background="#008000", font=(10), foreground="#fff", style="Bold.TLabel").grid(row=i, column=0, padx=5, pady=5, sticky="w")
            self.sliders[i].grid(row=i, column=1, padx=5, pady=5, sticky="w")
            
        self.submit_button = ttk.Button(form_frame, text="Submit", style="My.TButton", command=self.predict)
        self.submit_button.grid(row=8, column=0, columnspan=3, padx=5, pady=10, sticky="w")
        
        # Apply a custom style to the button
        self.style.configure("My.TButton", background='#00008B', foreground='#fff', padding=(10, 5))
        
        # Apply a custom style to the radio button
        self.style.configure("My.TRadiobutton", background='#006400',foreground="#fff",font=(8))

    def browse_resume(self):
        file_path = filedialog.askopenfilename(title="Select Resume", filetypes=[("PDF Files", "*.pdf"), ("Text Files", "*.txt"), ("All Files", "*.*")])
        # You can use the 'file_path' as needed, for example, display the file name or store it for submission.

if __name__ == "__main__":
    form = PersonalityForm()
    form.mainloop()